# Uncomment this line to define a global platform for your project
platform :ios, '10.3'

target 'RNEegMuseLib' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'libmuse', :git => 'https://github.com/nuks/podspec-libmuse.git'
  pod 'Functional.m', '~> 1.0'
end
